services:
    spring:
        expose:
            - 8090
        container_name: spring
        networks:
            - caddy
        labels:
            caddy: i11c102.p.ssafy.io
            caddy.handle_path: /api*
            caddy.handle_path.0_reverse_proxy: "{{upstreams 8090}}"
        image: spring:latest
        pull_policy: never
networks:
    caddy:
        external: true
        name: caddy
